spring:
  application:
    name:
      spring-kafka-batch-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch_demo
    username: root
    password: password
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: my-group
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: dummy-orders-v3
    bootstrap-servers: localhost:19092
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true